version: "3.9"
services:
  mongodb:
    image: mongo:latest
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  discovery:
    image: 'translink-gtfs-backend-discovery:latest'
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    volumes:
      - discovery-log:/home/log
    ports:
      - "8761:8761"
  gateway:
    image: 'translink-gtfs-backend-gateway:latest'
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
    environment:
      EUREKA_URL: http://discovery:8761
    depends_on:
      - discovery
    networks:
      - app-network
    volumes:
      - gateway-log:/home/log
    ports:
      - "8080:8080"
  data-initializer:
    image: 'translink-gtfs-backend-data-initializer:latest'
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: none
    depends_on:
      - discovery
      - mongodb
    env_file:
      - .env
    environment:
      EUREKA_URL: http://discovery:8761
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      REFRESH_DATA: "true"
    networks:
      - app-network
    volumes:
      - initializer-log:/home/log
  worker:
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 20s
    image: 'translink-gtfs-backend-worker:latest'
    depends_on:
      - discovery
      - mongodb
    env_file:
      - .env
    environment:
      EUREKA_URL: http://discovery:8761
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    networks:
      - app-network
  gtfs-service:
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 20s
    image: 'translink-gtfs-backend-gtfs-service:latest'
    depends_on:
      - discovery
      - mongodb
    env_file:
      - .env
    environment:
      EUREKA_URL: http://discovery:8761
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    networks:
      - app-network

volumes:
  mongo-data:
  discovery-log:
  gateway-log:
  initializer-log:

networks:
  app-network:
      name: app-network
      external: true