spring:
  application:
    name: gateway
  cloud:
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedHeaders: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gtfs
          uri: lb://gtfs-service
          predicates:
            - Path=/**

server:
  port: ${PORT:8080}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"